name: VanossFreedomMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 1.6
description: FREE OP Plugin made by Batho, for the VCF & Batdil Omegle server.
authors: [Madgeek1450, DarthSalamon, 8654, Bikkiester]

# plugin.yml is no longer used to define commands.
